import type { RouteObject } from "react-router";
import {
  type RouteConfig,
  route,
  index,
} from "@react-router/dev/routes";

const routes = [
  // Rota index para a página inicial
  index("./routes/home.tsx"),

  // Admin routes
  route("admin", "./routes/admin-layout.tsx", [
    index("./routes/admin/index.tsx"),
    route("init-db", "./routes/admin/init-db.tsx"),
    route("init-profiles", "./routes/admin/init-profiles.tsx"),
    route("make-admin", "./routes/admin/make-admin.tsx"),
    route("products", "./routes/admin/products.tsx"),
    route("colors", "./routes/admin/colors.tsx"),
    route("textures", "./routes/admin/textures.tsx"),
    route("quotes", "./routes/admin/quotes/index.tsx"),
    route("quotes/:id", "./routes/admin/quotes.$id.tsx"),
    route("users", "./routes/admin/users.tsx"),
    route("settings", "./routes/admin/settings.tsx"),
    route("reports", "./routes/admin/reports.tsx"),
    route("ai-color-assistant", "./routes/admin/ai-color-assistant.tsx"),
    route("api-webhooks", "./routes/admin/api-webhooks.tsx"),
    route("architecture", "./routes/admin/architecture.tsx"),
    route("backup-lgpd", "./routes/admin/backup-lgpd.tsx"),
    route("blog-posts", "./routes/admin/blog-posts.tsx"),
    route("blog-posts/new", "./routes/admin/blog-posts.new.tsx"),
    route("blog-posts/:id/edit", "./routes/admin/blog-posts.$id.edit.tsx"),
    route("bo-export", "./routes/admin/bo-export.tsx"),
    route("cad-plans", "./routes/admin/cad-plans.tsx"),
    route("ci-cd", "./routes/admin/ci-cd.tsx"),
    route("cloud-storage", "./routes/admin/cloud-storage.tsx"),
    route("collaborative-moodboards", "./routes/admin/collaborative-moodboards.tsx"),
    route("data-export", "./routes/admin/data-export.tsx"),
    route("digital-signature-admin", "./routes/admin/digital-signature-admin.tsx"),
    route("digital-signature", "./routes/admin/digital-signature.tsx"),
    route("dosage-formulas", "./routes/admin/dosage-formulas.tsx"),
    route("dosage-machines", "./routes/admin/dosage-machines.tsx"),
    route("dynamic-templates/:id/edit", "./routes/admin/dynamic-templates.$id.edit.tsx"),
    route("dynamic-templates", "./routes/admin/dynamic-templates.tsx"),
    route("editable-layers", "./routes/admin/editable-layers.tsx"),
    route("email-templates", "./routes/admin/email-templates.tsx"),
    route("final-testing", "./routes/admin/final-testing.tsx"),
    route("formula-history", "./routes/admin/formula-history.tsx"),
    route("formula-import-export", "./routes/admin/formula-import-export.tsx"),
    route("gamification", "./routes/admin/gamification.tsx"),
    route("generate-quote-pdf", "./routes/admin/generate-quote-pdf.tsx"),
    route("intelligent-reports", "./routes/admin/intelligent-reports.tsx"),
    route("magic-calculator", "./routes/admin/magic-calculator.tsx"),
    route("notification-settings", "./routes/admin/notification-settings.tsx"),
    route("offline-mode", "./routes/admin/offline-mode.tsx"),
    route("predictive-alerts", "./routes/admin/predictive-alerts.tsx"),
    route("production-reports", "./routes/admin/production-reports.tsx"),
    route("project-cases", "./routes/admin/project-cases.tsx"),
    route("quote-templates", "./routes/admin/quote-templates.tsx"),
    route("region-heatmap", "./routes/admin/region-heatmap.tsx"),
    route("schedule-emails", "./routes/admin/schedule-emails.tsx"),
    route("logo-settings", "./routes/admin/logo-settings.tsx"),
    route("system-logs", "./routes/admin/system-logs.tsx"),
    route("technical-config", "./routes/admin/technical-config.tsx"),
    route("technical-settings", "./routes/admin/technical-settings.tsx"),
    route("test-db", "./routes/admin/test-db.tsx"),
    route("tinting-machines", "./routes/admin/tinting-machines.tsx"),
  ]),

  // Outras rotas
  route("catalogo", "./routes/catalogo.tsx"),
  route("cores", "./routes/cores.tsx"),
  route("produto/:slug", "./routes/produto.$slug.tsx"),
  route("simulador", "./routes/simulador.tsx"),
  route("comparador", "./routes/comparador.tsx"),
  route("moodboard", "./routes/moodboard.tsx"),
  route("calculadora-rendimento", "./routes/calculadora-rendimento.tsx"),
  route("destaques-semana", "./routes/destaques-semana.tsx"),
  route("aplicacoes-tecnicas", "./routes/aplicacoes-tecnicas.tsx"),
  route("paleta-cores", "./routes/paleta-cores.tsx"),
  route("normas-tecnicas", "./routes/normas-tecnicas.tsx"),
  route("sobre", "./routes/sobre.tsx"),
  route("contato", "./routes/contato.tsx"),
  route("politica-de-privacidade", "./routes/politica-de-privacidade.tsx"),
  route("termos-de-uso", "./routes/termos-de-uso.tsx"),
  route("orcamento", "./routes/orcamento.tsx"),
  route("contato-consultor", "./routes/contato-consultor.tsx"),
  route("login", "./routes/login.tsx"),
  route("register", "./routes/register.tsx"),
  route("esqueci-senha", "./routes/esqueci-senha.tsx"),
  route("reset-password", "./routes/reset-password.tsx"),
  route("auth/callback", "./routes/auth/callback.tsx"),
  route("resend-confirmation", "./routes/resend-confirmation.tsx"),
  route("perfil", "./routes/perfil.tsx"),
  route("meus-projetos", "./routes/meus-projetos.tsx"),
  route("novo-projeto", "./routes/novo-projeto-redirect.tsx"),
  route("projects", "./routes/projects.tsx"),
  route("projects/:slug", "./routes/projects.$slug.tsx"),
  route("inspiracao", "./routes/inspiracao.tsx"),
  route("blog", "./routes/blog.tsx"),
  route("blog/:slug", "./routes/blog.$slug.tsx"),
  route("assinatura-orcamento", "./routes/assinatura-orcamento.tsx"),
  route("debug-user", "./routes/debug-user.tsx"),
  route("debug", "./routes/debug.tsx"),
  route("sustentabilidade", "./routes/sustentabilidade.tsx"),
  route("tecnicas-de-aplicacao", "./routes/tecnicas-de-aplicacao.tsx"),
  route("garantia", "./routes/garantia.tsx"),
  route("preparacao-de-superficies", "./routes/preparacao-de-superficies.tsx"),
  route("cuidados-e-manutencao", "./routes/cuidados-e-manutencao.tsx"),
  route("central-de-ajuda", "./routes/central-de-ajuda.tsx"),

  // API routes
  route("api/colors", "./routes/api/colors.ts"),
  route("api/ai/upgrade-realista", "./routes/api/ai/upgrade-realista.ts"),
  route("api/ai/upgrade-color", "./routes/api/ai/upgrade-color.ts"),
  route("api/ai/upgrade-texture", "./routes/api/ai/upgrade-texture.ts"),
  route("api/ai/apply-texture", "./routes/api/ai/apply-texture.tsx"),
  route("api/ai/usage", "./routes/api/ai/usage.ts"),
  route("api/quotes/send", "./routes/api/quotes/send.ts"),
  route("api/vendaerp/intencao-cor", "./routes/api/vendaerp/intencao-cor.ts"),
  route("api/vendaerp/processar", "./routes/api/vendaerp/processar.ts"),

  // Studio ProRevest routes
  route("studio", "./routes/studioprorevest.tsx"),
  route("studio/project/:projectId", "./routes/studio-project-redirect.tsx"),
  route("studio/new-project", "./routes/studio/new-project.tsx"),
  route("studio/editor/:projectSlug", "./routes/studio/editor/[projectSlug].tsx"),
  route("studioprorevest", "./routes/studioprorevest-redirect.tsx"),
] satisfies RouteConfig;

export default routes;
